# replace "project-id-here" in the three targets below with your actual project(s)
# Supports two single targets (Test and Stage) and one multi-target (Prod)
apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: pop-stats-multitarget
description: pop-stats application delivery pipeline with canary
serialPipeline:
  stages:
  - targetId: test
  - targetId: staging
    profiles: [staging]
    strategy:
      canary:
        runtimeConfig:
          kubernetes:
            serviceNetworking:
              service: "pop-stats"
              deployment: "pop-stats"
        canaryDeployment:
          percentages: [0]
          verify: false       
  - targetId: prod
    profiles: [prod]
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: test
description: test cluster
gke:
  cluster: projects/riccardo-blog-test-v1/locations/us-central1/clusters/testcluster
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: staging
description: staging cluster
gke:
  cluster: projects/riccardo-blog-test-v1/locations/us-central1/clusters/stagingcluster
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
description: prod multi-target
requireApproval: true
multiTarget:
   targetIds: [ prod-us-east, prod-us-central, prod-us-west ]
---  

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod-us-central
description: gke cluster in US Central region
gke:
  cluster: projects/riccardo-blog-test-v1/locations/us-central1/clusters/prodcluster
---  

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod-us-east
description: gke cluster in US East region
gke:
  cluster: projects/riccardo-blog-test-v1/locations/us-east1/clusters/prodcluster-useast1
---  

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod-us-west
description: gke cluster in US West region
gke:
  cluster: projects/riccardo-blog-test-v1/locations/us-west1/clusters/prodcluster-uswest1
