# replace "project-id-here" in the three targets below with your actual project(s)
apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: pop-stats-pipeline
description: pop-stats application delivery pipeline with canary
serialPipeline:
  stages:
  - targetId: test
  - targetId: staging
    profiles: [staging]
    strategy:
      canary:
        runtimeConfig:
          kubernetes:
            serviceNetworking:
              service: "pop-stats"
              deployment: "pop-stats"
        canaryDeployment:
          percentages: [0]
          verify: false  
  - targetId: prod
    profiles: [prod]
    strategy:
      canary:
        runtimeConfig:
          kubernetes:
            serviceNetworking:
             service: "pop-stats"
             deployment: "pop-stats"
        canaryDeployment:
          percentages: [25,50]
          verify: false  
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: test
description: test cluster
gke:
  cluster: projects/end-to-end-demo-v1/locations/us-central1/clusters/testcluster
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: staging
description: staging cluster
gke:
  cluster: projects/end-to-end-demo-v1/locations/us-central1/clusters/stagingcluster
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
description: prod cluster
requireApproval: true
gke:
  cluster: projects/end-to-end-demo-v1/locations/us-central1/clusters/prodcluster

