# replace "project-id-here" in the three targets below with your actual project(s)
apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: pop-stats-pipeline
description: pop-stats application delivery pipeline
serialPipeline:
 stages:
 - targetId: test
 - targetId: staging
<<<<<<< HEAD
   profiles:
   - staging
   canary:
     runtimeConfig:
       kubernetes:
         serviceNetworking:
           service: "my-service"
           deployment: "my-deployment"
      canaryDeployment:
        percentages: [50]
        verify: false     
=======
   profiles: [staging]
>>>>>>> f163cd99e2e62f4584654cac8fc285fef60925f7
 - targetId: prod
   profiles: [prod]
   strategy:
     standard:
       verify: true
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: test
description: test cluster
gke:
  cluster: projects/project-id-here/locations/us-central1/clusters/testcluster
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: staging
description: staging cluster
gke:
  cluster: projects/project-id-here/locations/us-central1/clusters/stagingcluster
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
description: prod cluster
requireApproval: true
gke:
  cluster: projects/project-id-here/locations/us-central1/clusters/prodcluster

