apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: pop-stats
build:
# Uncomment if you're using minikube for local dev and don't want to push to Artifact Registry
#  local: 
#    push: false
  artifacts:
  - image: pop-stats
    context: app
    docker:
      dockerfile: Dockerfile
manifests:
  kustomize:
    paths:
      - k8s/overlays/dev
portForward:
- resourceType: deployment
  resourceName: pop-stats
  port: 8080
  localPort: 8080
profiles:
  - name: staging
    manifests:
      kustomize:
        paths: 
          - k8s/overlays/staging
  - name: prod
    manifests:
      kustomize:
        paths: 
          - k8s/overlays/prod
    verify:
    - name: after-deploy-verification
      container:
        name: after-deploy-container
        image: alpine
        command: ["bin/sh"]
        args: ["-c", "wget http://130.211.209.216:8080/"]            

         
