apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: pop-stats
build:
# Uncomment if you're using minikube for local dev and don't want to push to Artifact Registry
#  local: 
#    push: false
  artifacts:
  - image: pop-stats
    context: app
    docker:
      dockerfile: Dockerfile
deploy:
  kustomize:
    paths: 
      - k8s/overlays/dev
portForward:
- resourceType: deployment
  resourceName: pop-stats
  port: 8080 
  localPort: 8080
verify:
- name: after-deploy-verification
  contianer:
    name: after-deploy-container
    image: alpine:3:16
    command: ["bin/sh"]
    args: ["-c","wget http://http://34.122.255.169:8080/"  
profiles:
  - name: staging
    deploy:
      kustomize:
        paths: 
          - k8s/overlays/staging
  - name: prod
    deploy:
      kustomize:
        paths: 
          - k8s/overlays/prod

         
