apiVersion: autoscaling/v2
#apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: pop-stats
spec:
  scaleTargetRef:
    kind: deployment
    name: pop-stats
  minReplicas: 2
  maxReplicas: 2
#  maxReplicas: 
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80